/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:da5310c3-c920-4dee-9b05-344e4a8f53da",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_LuU4TrJNT",
    "aws_user_pools_web_client_id": "4to56up96iicmpdkfscs1e5jeo",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://t7xiwncvh5gklcq6upyj3o4t64.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3dpkyvpa2rckxlj7ota36to6gu",
    "aws_user_files_s3_bucket": "amplifyapp6f605fa666d04563a2c56faf82717589222816-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-2"
};


export default awsmobile;
